export const coastalRegions = [
    "North Coast",
    "West Coast",
    "South Coast",
    "Gascoyne Coast",
  ];

export const regions = [
  "All - statewide",
  "Gascoyne",
  "Goldfields - Esperance",
  "Great Southern",
  "Kimberley",
  "Mid West",
  "Peel",
  "Perth",
  "Pilbara",
  "South West",
  "Wheatbelt"
]

  
  export const landRegions = [
    "Gascoyne",
    "Goldfields-Esperance",
    "Great Southern",
    "Kimberley",
    "Peel",
    "Perth Metro",
    "Pilbara",
    "South West",
    "Wheatbelt",
  ];
  
  export const districts = [
    "Central Coast",
    "Gascoyne",
    "Great Southern WA",
    "Mid-west",
    "Perth Metro",
    "South",
    "South West",
    "South/Perth Metro",
    "SW/Perth Metro",
    "Western Australia",
  ];
  
  
  export const cities = [
    "Albany",
    "Banksia Grove",
    "Bayswater",
    "Bently",
    "Butler",
    "Bunbury",
    "Busselton",
    "Carine",
    "Castletown",
    "City Beach",
    "Cottesloe",
    "Cowaramup",
    "Dalyellup",
    "Drummond Cove",
    "East Fremantle",
    "Elleker",
    "Exmouth",
    "Falcon",
    "Fremantle",
    "Geraldton",
    "Guilderton",
    "Hilton",
    "Joondalup",
    "Jolimont",
    "Jurien Bay",
    "Kalgan",
    "Kardinya",
    "Kingsley",
    "Manjimup",
    "Mandurah",
    "Maylands",
    "Mosman Park",
    "Mount Lawley",
    "Nedlands",
    "North Beach",
    "Palmyra",
    "Perth",
    "Quinns Rocks",
    "Santa Barbara",
    "Scarborough",
    "Taalinup Augusta",
    "Walpole",
    "Wembley",
    "Piara Waters",
  ];

  export const stakeholderTypes = [
    "Commonwealth Government",
    "State Government",
    "Local Government",
    "Private Organisation",
    "Natural Resource Management Group",
    "Community and Individual",
    "Traditional Owner",
  ]
  
  export const subclusterTypes = [
      'Aboriginal Corporation',
      'Animal Rescue',
      'Biosecurity',
      'Community Landcare',
      'Consultant',
      'Government',
      'Individual',
      'Landcare Conservation District Committee',
      'Mining',
      'Native Title Representative Body',
      'Non Government Organisation',
      'Nursery',
      'Pastoralist or Station',
      'Peak Body',
      'Port Authority',
      'Prescribed Body Corporate',
      'Primary Resources',
      'Reference or Advisory Group',
      'Research and Education',
      'Tourism'
  ]