export const coastalRegions = [
    "North Coast",
    "West Coast",
    "South Coast",
    "Gascoyne Coast",
  ];

export const regions = [
    "Central Coast",
    "Wheatbelt",
    "Gascoyne",
    "Great Southern WA",
    "Mid-west",
    "Perth",
    "SW",
    "South",
    "South West",
    "WA",
    "Western Australia"
]
  
  export const landRegions = [
    "Gascoyne",
    "Goldfields-Esperance",
    "Great Southern",
    "Kimberley",
    "Peel",
    "Perth Metro",
    "Pilbara",
    "South West",
    "Wheatbelt",
  ];
  
  export const districts = [
    "Central Coast",
    "Gascoyne",
    "Great Southern WA",
    "Mid-west",
    "Perth Metro",
    "South",
    "South West",
    "South/Perth Metro",
    "SW/Perth Metro",
    "Western Australia",
  ];
  
  
  export const cities = [
    "Albany",
    "Banksia Grove",
    "Bayswater",
    "Bently",
    "Butler",
    "Bunbury",
    "Busselton",
    "Carine",
    "Castletown",
    "City Beach",
    "Cottesloe",
    "Cowaramup",
    "Dalyellup",
    "Drummond Cove",
    "East Fremantle",
    "Elleker",
    "Exmouth",
    "Falcon",
    "Fremantle",
    "Geraldton",
    "Guilderton",
    "Hilton",
    "Joondalup",
    "Jolimont",
    "Jurien Bay",
    "Kalgan",
    "Kardinya",
    "Kingsley",
    "Manjimup",
    "Mandurah",
    "Maylands",
    "Mosman Park",
    "Mount Lawley",
    "Nedlands",
    "North Beach",
    "Palmyra",
    "Perth",
    "Quinns Rocks",
    "Santa Barbara",
    "Scarborough",
    "Taalinup Augusta",
    "Walpole",
    "Wembley",
    "Piara Waters",
  ];

  